---
- name: "update apt."
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt"
  become: true
  apt:
    upgrade: yes

- name: install deps
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: extract artifact
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: start app
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start