
---
- name: Creates backend directory
  file:
    path: ~/backend/
    state: directory

- name: Copy and unarchive artifact
  unarchive:
    src: ../../artifact.tar.gz
    dest: ~/backend

- name: Start PM2
  shell: |
    cd ~/backend/dist
    pm2 start main.js